---
- name: Install apache
  become: true
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Change apache to specified port
  become: true
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: 'Listen {{ web_port }}'

# Add these tasks before starting httpd
- name: Install policycoreutils-python for SELinux port management
  become: true
  ansible.builtin.yum:
    name: policycoreutils-python-utils
    state: present

- name: Allow httpd to listen on custom port
  become: true
  ansible.builtin.shell: semanage port -a -t http_port_t -p tcp {{ web_port }}
  register: semanage_result
  failed_when:
  - semanage_result.rc != 0
  - '"already defined" not in semanage_result.stderr'
  changed_when: semanage_result.rc == 0

- name: Set nis_enabled flag on and keep it persistent across reboots
  become: true
  ansible.posix.seboolean:
    name: nis_enabled
    state: true
    persistent: true

- name: Start httpd
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

- name: Create HTML report
  become: true
  ansible.builtin.template:
    src: report.j2
    dest: "{{ report_dir }}/index.html"
    mode: "644"

- name: Copy CSS over
  become: true
  ansible.builtin.copy:
    src: "css"
    dest: "{{ report_dir }}"
    directory_mode: true
    mode: "644"

- name: Copy CSS over
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ report_dir }}"
    directory_mode: true
    mode: "644"
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "router.png"

- name: Debug hostvars
  ansible.builtin.debug:
    msg: "{{ hostvars[inventory_hostname] }}"

# roles/build_report/tasks/main.yml

# First debug the facts
- name: Debug connection info
  ansible.builtin.debug:
    msg: "Current host: {{ inventory_hostname }}"

# Then update the display link task
- name: Display link to inventory report
  ansible.builtin.debug:
    msg: "Report available at http://{{ inventory_hostname }}:{{ web_port }}/index.html"
