- name: Load corresponding network platform
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_network_os }}.yml"
    - "unsupported_platform.yml"

- name: Reset the connection
  ansible.builtin.meta: reset_connection

- name: Wait for the network device to reload
  ansible.builtin.wait_for_connection:
    delay: 10

# - name: Wait for SSH port availability
#   ansible.builtin.wait_for:
#     host: "{{ inventory_hostname }}"
#     port: 22
#     timeout: 300
#     state: started
#   register: ssh_result
#   delegate_to: localhost
#   when: ping_result is success

- name: Get the device uptime
  vars:
    ansible_connection: network_cli
  ansible.netcommon.cli_command:
    command: "{{ platform_uptime_command[ansible_network_os] }}"
  register: output

- name: Show the device uptime
  ansible.builtin.debug:
    msg: "{{ output['stdout_lines'][0] }}"
