---
# roles/build_report_container/tasks/main.yml
- name: Get timestamp
  run_once: true
  ansible.builtin.set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    date_stamp: "{{ lookup('pipe', 'date +%Y%m%d') }}"

- name: Debug timestamp and paths
  ansible.builtin.debug:
    msg:
    - "Timestamp: {{ timestamp }}"
    - "Date stamp: {{ date_stamp }}"
    - "Report type: {{ report_type }}"
    - "Report directory: {{ report_dir }}"

- name: Create report directory
  ansible.builtin.file:
    path: "{{ report_dir }}"
    state: directory
    mode: "775"
    recurse: true

- name: Create dated directory
  ansible.builtin.file:
    path: "{{ report_dir }}/{{ date_stamp }}"
    state: directory
    mode: "775"
    recurse: true

- name: Include selinux role
  vars:
    selinux_fcontexts:
      - {target: '{{ report_dir }}(/.*)?', setype: 'httpd_sys_content_t', state: 'present'}
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.selinux

- name: Debug file paths
  ansible.builtin.debug:
    msg:
    - "File path: {{ report_dir }}"
    - "Full glob path: {{ report_dir + '/*/' }}"

- name: List available reports (debug)
  ansible.builtin.find:
    paths: "{{ report_dir }}"
    recurse: true
    patterns: "*-patching-report.html"
    file_type: file
  register: all_reports

- name: Debug found reports
  ansible.builtin.debug:
    var: all_reports

- name: Ensure Nginx container is running
  containers.podman.podman_container:
    name: nginx_container
    image: docker.io/nginx:stable-alpine3.20-slim
    state: started
    ports:
      - "{{ web_port }}:80"
    volumes:
      - "{{ report_dir }}:/usr/share/nginx/html:Z"
    # restart_policy: always
    recreate: true

- name: Ensure report directory permissions
  ansible.builtin.file:
    path: "{{ report_dir }}"
    state: directory
    mode: "775"
    recurse: true

- name: Create HTML report from template
  template:
    src: report.j2
    dest: "{{ report_dir }}/{{ date_stamp }}/{{ timestamp }}_switch-firmware-{{ report_type }}-patching-report.html"
    mode: '0644'

- name: Create main index.html file
  template:
    src: index.j2
    dest: "{{ report_dir }}/index.html"
    mode: '0644'

- name: Copy CSS over
  ansible.builtin.copy:
    src: "css"
    dest: "{{ report_dir }}"
    directory_mode: true
    mode: "775"

- name: Copy CSS over
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ report_dir }}"
    directory_mode: true
    mode: "644"
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "router.png"
    - "network-switch-pre-patching.png"
    - "network-switch-post-patching.png"

- name: Retrieve public IP address
  ansible.builtin.command: curl https://ifconfig.me
  register: public_ip_report
  ignore_errors: true

- name: Display link to inventory report
  ansible.builtin.debug:
    msg:
      - "Please go to http://{{ public_ip_report.stdout | default(ansible_fqdn) }}:{{ web_port }}"
