---
- name: Retrieve facts for network infrastructure
  hosts: network
  gather_facts: false

  tasks:
    - name: Load read interfaces role
      ansible.builtin.include_role:
        name: "../roles/facts"

- name: Build report with facts
  hosts: ansible-1
  become: true
  gather_facts: false

  tasks:

    - name: Build pre-patching report
      ansible.builtin.include_role:
        name: "../roles/build_report_container"
      vars:
        report_type: "pre"

    - name: Build post-patching report
      ansible.builtin.include_role:
        name: "../roles/build_report_container"
      vars:
        report_type: "post"